#!/usr/bin/env tsx
/**
 * Generate SQL seed fragments + mirror schemas from canonical config.
 *
 * Source of truth: config/narrative-engine/
 * Outputs:
 *   - supabase/seed/generated/narrative-config.sql
 *   - supabase/seed/schemas/*.json (mirrored)
 *
 * Run: npm run config:generate
 */
import { config as loadDotenv } from 'dotenv';
import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { getConfigRoot, loadNarrativeConfig, resetNarrativeConfigCache } from '../src/config/narrativeConfig.js';

const API_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const REPO_ROOT = join(API_ROOT, '..');
const GENERATED_DIR = join(REPO_ROOT, 'supabase/seed/generated');
const SCHEMAS_OUT = join(REPO_ROOT, 'supabase/seed/schemas');

loadDotenv({ path: join(API_ROOT, '.env') });

function sqlEscape(str: string): string {
  return str.replace(/'/g, "''");
}

function sqlJson(obj: unknown): string {
  return `'${sqlEscape(JSON.stringify(obj))}'::jsonb`;
}

function generateConfigSql(): string {
  resetNarrativeConfigCache();
  const { meta, enums, prompts, schemas, resolved } = loadNarrativeConfig();

  const lines: string[] = [
    '-- AUTO-GENERATED by narrative-engine-api/scripts/generate-config-seed.ts',
    `-- Config version: ${meta.version}`,
    '-- Do not edit manually. Edit config/narrative-engine/ then run: npm run config:generate',
    '',
  ];

  lines.push('-- enum_definitions');
  for (const [enumKey, values] of Object.entries(enums)) {
    const payload = values.map((v) => ({ key: v.key, label: v.label, active: true }));
    lines.push(
      `INSERT INTO enum_definitions (enum_key, values, engine_scope) VALUES ('${enumKey}', ${sqlJson(payload)}, '{narrative}') ON CONFLICT (enum_key) DO UPDATE SET values = EXCLUDED.values;`,
    );
  }
  lines.push('');

  lines.push('-- schema_registry');
  for (const [schemaKey, jsonSchema] of Object.entries(schemas)) {
    lines.push(
      `INSERT INTO schema_registry (schema_key, json_schema) VALUES ('${schemaKey}', ${sqlJson(jsonSchema)}) ON CONFLICT (schema_key) DO UPDATE SET json_schema = EXCLUDED.json_schema;`,
    );
  }
  lines.push('');

  lines.push('-- prompt_templates');
  for (const layerKey of Object.keys(prompts)) {
    const layer = prompts[layerKey as keyof typeof prompts];
    const resolvedPrompt = resolved[layerKey as keyof typeof resolved];
    lines.push(
      `INSERT INTO prompt_templates (engine_type, layer_key, version, system_prompt, user_prompt_template, variables, output_schema_ref, is_active) VALUES ('${meta.engine_type}', '${layer.layer_key}', '${layer.version}', '${sqlEscape(resolvedPrompt.system_prompt)}', '${sqlEscape(resolvedPrompt.user_prompt_template)}', '[]', '${layer.output_schema_ref}', true) ON CONFLICT (engine_type, layer_key, version) DO UPDATE SET system_prompt = EXCLUDED.system_prompt, user_prompt_template = EXCLUDED.user_prompt_template, output_schema_ref = EXCLUDED.output_schema_ref, is_active = EXCLUDED.is_active;`,
    );
  }
  lines.push('');

  return lines.join('\n');
}

function mirrorSchemas() {
  const schemasDir = join(getConfigRoot(), 'schemas');
  mkdirSync(SCHEMAS_OUT, { recursive: true });
  for (const file of readdirSync(schemasDir).filter((f) => f.endsWith('.json'))) {
    copyFileSync(join(schemasDir, file), join(SCHEMAS_OUT, file));
  }
}

function main() {
  mkdirSync(GENERATED_DIR, { recursive: true });
  const sql = generateConfigSql();
  const outPath = join(GENERATED_DIR, 'narrative-config.sql');
  writeFileSync(outPath, sql);
  mirrorSchemas();
  console.log('Generated:', outPath);
  console.log('Mirrored schemas to:', SCHEMAS_OUT);
  console.log('Apply to DB: npm run config:sync');
  console.log('Or SQL: supabase db query --linked -f supabase/seed/generated/narrative-config.sql');
}

main();
